### ISSUE TITLE
Build error -Wstringop-truncation

### ISSUE THREAD

**Issue by mheidt** [moddevices/mod-ttymidi#11]
https://stackoverflow.com/questions/50198319/gcc-8-wstringop-truncation-what-is-the-good-practice

if you surround the
strncpy of arguments->serialdevice

with

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstringop-truncation"

and
#pragma GCC diagnostic pop

the build works again.
But I wonder, why the strncopy of arguments->name don't break.
Only because serialdevice is first in the struct?

**Comment by jofemodo** [comment]
This should fix the compilation problem. Seems that strncpy is being deprecated by main compilers. First MS and now GCC. A classic function, but very prone to breaking code and causing Buffer Overflows and SegFaults. It's been declared unwanted and enemy of "clean code". You shouldn't use it for anything because it doesn't do what is supposed to do, although the documentation is very clear about what it does ... OK ... I read a little bit about the reasons to do it, and i decided i will never use it again ;-)

Changing ttymidi takes about 2 mins, but if you base code is big, it can be a little bit annoying. But in that cases, you can simply disable the warning with a compiler option.

**Comment by falkTX** [comment]
So if it is being deprecated, what is the replacement?
There are completely valid use cases for `strncpy`, seems like deprecating something due to most devs misusing it, which feels quite sad to me...

**Comment by mheidt** [comment]
See https://github.com/moddevices/mod-ttymidi/pull/12

**Comment by jofemodo** [comment]
The "snprintf" is a quite good replacement. Of course, there is a lot of "good" issues for the strncpy function, but it seems that "compiler masters" have decided to put some press over developers for avoiding bad uses.
In fact, in the ttymidi source there was 5 calls to strncpy, but only 3 warnings were generated because  2 of the calls were "good" uses.
Anyway, the important thing is fixing mod-ttymidi so it can be build with modern gcc, and we have several options:

+ replace strncpy by other function. I used snprintf because it's also in stdio, so the change is minimal.

+ use PRAGMA for disabling the warning locally in the code. I personally don't like this at all.

+ disable the warning using a compiler option in the Makefile. It's OK for me, but i prefer the first option.

Regards,

**Comment by falkTX** [comment]
Fixed now

**Comment by jofemodo** [comment]
This:

`strncpy(arguments->serialdevice, arg, MAX_DEV_STR_LEN-1);`

doesn't avoid the problem with strncpy unless you put a NULL in the last byte of arguments->serialdevice (or the char array is initialized to 0s).

The addition of the compiler option avoid the compiler warnings, of course ;-)

**Comment by falkTX** [comment]
But it does. variables declared static are initialized to 0, so the last byte of that variable is always going to be 0 (unless we overwrite it)
The compiler knows this, so it does not complain.

**Comment by jofemodo** [comment]
OK! It's true:

`static arguments_t arguments;`

 although it's not very explicit. I think it's better to abandon strncpy, but it's your code, your rules ;-)

**Comment by falkTX** [comment]
What I read online so far did not convince me to move away from `strncpy`, specially now with compiler warnings
